# Generated by Django 5.0 on 2025-12-11 10:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ism")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Familiya"),
                ),
                (
                    "speciality",
                    models.CharField(
                        choices=[
                            ("dentist", "Stomatolog"),
                            ("cardiologist", "Kardiolog"),
                            ("surgeon", "Xirurg"),
                            ("dermatologist", "Dermatolog"),
                            ("pediatrician", "Pediatr"),
                        ],
                        default="dentist",
                        max_length=50,
                        verbose_name="Mutaxassislik",
                    ),
                ),
                ("bio", models.TextField(verbose_name="Shifokor haqida")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctors/", verbose_name="Rasm"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Qabul narxi"
                    ),
                ),
                (
                    "work_start_time",
                    models.TimeField(
                        default=datetime.time(9, 0), verbose_name="Ish boshlanish vaqti"
                    ),
                ),
                (
                    "work_end_time",
                    models.TimeField(
                        default=datetime.time(17, 0), verbose_name="Ish tugash vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shifokor",
                "verbose_name_plural": "Shifokorlar",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Sana")),
                ("time", models.TimeField(verbose_name="Vaqt")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("confirmed", "Tasdiqlandi"),
                            ("cancelled", "Bekor qilindi"),
                            ("completed", "Yakunlandi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Shikoyat"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bemor",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="booking.doctor",
                        verbose_name="Shifokor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qabul",
                "verbose_name_plural": "Qabullar",
                "ordering": ["-date", "-time"],
                "unique_together": {("doctor", "date", "time")},
            },
        ),
    ]
