# Generated by Django 5.0 on 2025-12-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="telephone",
            field=models.CharField(
                default="doctor@doctor.com", max_length=15, verbose_name="Telefon raqam"
            ),
            preserve_default=False,
        ),
    ]
