# Generated by Django 5.0 on 2025-12-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_doctor_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="diagnosis",
            field=models.TextField(blank=True, null=True, verbose_name="Tashxis"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="prescription",
            field=models.TextField(blank=True, null=True, verbose_name="Retsept"),
        ),
    ]
