# Generated by Django 5.0 on 2025-12-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_appointment_diagnosis_appointment_prescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="speciality",
            field=models.CharField(
                choices=[
                    ("Stomatolog", "🦷 Stomatolog"),
                    ("Kardiolog", "❤️ Kardiolog"),
                    ("Xirurg", "🔪 Xirurg"),
                    ("Dermatolog", "🧴 Dermatolog"),
                    ("Pediatr", "👶 Pediatr"),
                    ("Terapevt", "🩺 Terapevt"),
                ],
                max_length=50,
                verbose_name="Mutaxassisligi",
            ),
        ),
    ]
